services:
  frontend:
    build:
      context: ../frontend/react   
      dockerfile: Dockerfile
      args:
        NGINX_CONF_PATH: ../../infra/nginx.conf
    container_name: frontend
    ports:
      - "3000:80"
    restart: always
